"use client";
import { useTranslation } from "react-i18next";
import GlassMainLayout from "./Common/GlassMainLayout";
import ProjectCard from "./ProjectCard";
import SectionTitle from "./SectionTitle";
import TechBadge from "./TechBadge";

export default function ProjectSection() {
  const { t } = useTranslation();
  return (
    <section>
      <GlassMainLayout>
        <SectionTitle title={t("projects.title")} />
        <div className="grid grid-cols-1 md:grid-cols-2 gap-2">
          <ProjectCard
            title={t("projects.project1.name")}
            description={
              t("projects.project1.description")
            }
            imageUrl={"/projectScreenshots/portfolio.jpg"}
            link={"https://myportfolio.com"}
          >
            <TechBadge
              iconUrl={"/commonIcons/react.svg"}
              link={"https://react.dev/"}
            />
            <TechBadge
              iconUrl={"/commonIcons/typescript.svg"}
              link={"https://www.typescriptlang.org/"}
            />
            <TechBadge
              iconUrl={"/commonIcons/tailwindcss.svg"}
              link={"https://tailwindcss.com/"}
            />
            <TechBadge
              iconUrl={"/commonIcons/nextjs.svg"}
              link={"https://nextjs.org/"}
            />
            <TechBadge
              iconUrl={"/commonIcons/daisyui.svg"}
              link={"https://daisyui.com/"}
            />
            <TechBadge
              iconUrl={"/commonIcons/i18next.svg"}
              link={"https://www.i18next.com/"}
            />
          </ProjectCard>
          <ProjectCard
            title={t("projects.project2.name")}
            description={
              t("projects.project2.description")
            }
            imageUrl={"/projectScreenshots/e-commerce.jpg"}
          >
            <TechBadge
              iconUrl={"/commonIcons/typescript.svg"}
              link={"https://www.typescriptlang.org/"}
            />
            <TechBadge
              iconUrl={"/commonIcons/tailwindcss.svg"}
              link={"https://tailwindcss.com/"}
            />
            <TechBadge
              iconUrl={"/commonIcons/nextjs.svg"}
              link={"https://nextjs.org/"}
            />
            <TechBadge
              iconUrl={"/commonIcons/mercadopago.svg"}
              link={"https://www.mercadopago.com/"}
            />
            <TechBadge
              iconUrl={"/commonIcons/daisyui.svg"}
              link={"https://daisyui.com/"}
            />
            <TechBadge
              iconUrl={"/commonIcons/redux.svg"}
              link={"https://redux.js.org/"}
            />
          </ProjectCard>
          <ProjectCard
            title={t("projects.project3.name")}
            description={t("projects.project3.description")}
            imageUrl="/projectScreenshots/calcula-carrito.jpg"
          >
            <TechBadge
              iconUrl={"/commonIcons/react.svg"}
              link={"https://reactnative.dev/"}
            />
            <TechBadge
              iconUrl={"/commonIcons/expo.svg"}
              link={"https://expo.dev/"}
            />
            <TechBadge
              iconUrl={"/commonIcons/typescript.svg"}
              link={"https://www.typescriptlang.org/"}
            />
            <TechBadge
              iconUrl={"/commonIcons/nativewind.svg"}
              link={"https://www.nativewind.dev/"}
            />
            <TechBadge
              iconUrl={"/commonIcons/uikitten.png"}
              link={"https://akveo.github.io/react-native-ui-kitten/"}
            />
          </ProjectCard>
          <ProjectCard
            title={t("projects.project4.name")}
            description={
              t("projects.project4.description")
            }
            imageUrl={"/projectScreenshots/landingAudifonos.jpg"}
          >
            <TechBadge
              iconUrl={"/commonIcons/react.svg"}
              link={"https://react.dev/"}
            />
            <TechBadge
              iconUrl={"/commonIcons/typescript.svg"}
              link={"https://www.typescriptlang.org/"}
            />
            <TechBadge
              iconUrl={"/commonIcons/tailwindcss.svg"}
              link={"https://tailwindcss.com/"}
            />
            <TechBadge
              iconUrl={"/commonIcons/nextjs.svg"}
              link={"https://nextjs.org/"}
            />
          </ProjectCard>
          <ProjectCard
            title={t("projects.project5.name")}
            description={t("projects.project5.description")}
            imageUrl={"/projectScreenshots/turnero.jpg"}
          >
            <TechBadge
              iconUrl={"/commonIcons/react.svg"}
              link={"https://react.dev/"}
            />
            <TechBadge
              iconUrl={"/commonIcons/typescript.svg"}
              link={"https://www.typescriptlang.org/"}
            />
            <TechBadge
              iconUrl={"/commonIcons/tailwindcss.svg"}
              link={"https://tailwindcss.com/"}
            />
            <TechBadge
              iconUrl={"/commonIcons/nextjs.svg"}
              link={"https://nextjs.org/"}
            />
            <TechBadge
              iconUrl={"/commonIcons/daisyui.svg"}
              link={"https://daisyui.com/"}
            />
            <TechBadge
              iconUrl={"/commonIcons/nextjs.svg"}
              link={"https://nextjs.org/"}
            />
            <TechBadge
              iconUrl={"/commonIcons/redux.svg"}
              link={"https://redux.js.org/"}
            />
          </ProjectCard>
        </div>
      </GlassMainLayout>
    </section>
  );
}
